import os
import re
import logging
import subprocess
import traceback
from xml.dom import minidom
from xml.etree.ElementTree import Element, SubElement, tostring

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
ICONS_DIR = os.path.join(BASE_DIR, "icons")
OUTPUT_DIR = BASE_DIR

def sanitize_name(name: str, used_names: set) -> str:
    base = os.path.splitext(name)[0]
    base = re.sub(r"[^a-zA-Z0-9]+", "_", base)
    base = base.upper()
    if base and base[0].isdigit():
        base = "_" + base
    new_name = base
    counter = 2
    while new_name in used_names:
        new_name = f"{base}_{counter}"
        counter += 1
    used_names.add(new_name)
    return new_name

# === Per-theme generate functions ===

def generate_qrc(theme_name: str, theme_dir: str, output_qrc_path: str) -> bool:
    """Generate .qrc file for a theme. Returns True if any SVG files found."""
    logger.info(f"[{theme_name}] Generating .qrc...")
    rcc = Element("RCC")
    qresource = SubElement(rcc, "qresource", prefix=f"/")
    found_any = False

    for root, _, files in os.walk(theme_dir):
        for file in files:
            if file.lower().endswith(".svg"):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, BASE_DIR).replace("\\", "/")
                SubElement(qresource, "file").text = rel_path
                logger.info(f" + {rel_path}")
                found_any = True

    if not found_any:
        logger.warning(f"[{theme_name}] No .svg files found in {theme_dir}.")
        return False

    xml_str = tostring(rcc, encoding="utf-8").decode("utf-8")
    dom = minidom.parseString(xml_str)
    pretty_xml = "\n".join(dom.toprettyxml(indent="  ").splitlines()[1:])
    with open(output_qrc_path, "w", encoding="utf-8") as f:
        f.write(pretty_xml)
    logger.info(f"[{theme_name}] .qrc generated at {output_qrc_path}")
    return True

def generate_icon_class(theme_name: str, theme_dir: str):
    """Generate Python icon class for a theme."""
    class_name = f"{theme_name.capitalize()}Icon"
    output_path = os.path.join(OUTPUT_DIR, f"{theme_name}_icon.py")
    logger.info(f"[{theme_name}] Generating icon class: {class_name} -> {output_path}")

    used_names = set()
    rc_module_name = f"resources_{theme_name}_rc"
    lines = [
        "# Auto-generated by icon_resource_generator.py - Do not edit manually",
        "# Generated on: 2025-08-16",
        "",
        "from PyQt5.QtGui import QIcon, QPixmap, QColor, QPainter",
        "from PyQt5.QtSvg import QSvgRenderer",
        "from PyQt5.QtCore import QSize, Qt",
        "",
        f"from . import {rc_module_name}",
        ""
        "class IconAccessor(str):",
        "    def __eq__(self, other):",
        "        return str(self) == str(other)",
        "",
        "    def __call__(self, color: str = None, size: QSize = QSize(16,16)) -> QIcon:",
        "        if color is None or not self.lower().endswith('.svg'):",
        "            return QIcon(self)",
        "",
        "        renderer = QSvgRenderer(self)",
        "        pixmap = QPixmap(size)",
        "        pixmap.fill(Qt.transparent)",
        "        painter = QPainter(pixmap)",
        "        renderer.render(painter)",
        "        painter.setCompositionMode(QPainter.CompositionMode_SourceIn)",
        "        painter.fillRect(pixmap.rect(), QColor(color))",
        "        painter.end()",
        "        return QIcon(pixmap)",
        "",
        "class ThemeIconMeta(type):",
        "    def __new__(mcs, name, bases, attrs):",
        "        new_attrs = {}",
        "        for key, value in attrs.items():",
        "            if isinstance(value, str) and value.startswith(':/'):",
        "                new_attrs[key] = IconAccessor(value)",
        "            else:",
        "                new_attrs[key] = value",
        "        return super().__new__(mcs, name, bases, new_attrs)",
        "",
        f"class {class_name}(metaclass=ThemeIconMeta):",
        f"    \"\"\"Auto-generated icons for the '{theme_name}' theme.\"\"\"",
    ]

    has_any = False
    for root, _, files in os.walk(theme_dir):
        for file in sorted(files):
            if file.lower().endswith((".svg", ".png", ".ico")):
                const_name = sanitize_name(file, used_names)
                rel_path = os.path.relpath(os.path.join(root, file), ICONS_DIR).replace("\\", "/")
                lines.append(f"    {const_name} = IconAccessor(':icons/{rel_path}')")
                has_any = True

    if not has_any:
        lines.append("    pass")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"[{theme_name}] Icon class generated at {output_path}")

def compile_qrc(input_qrc: str, output_py: str):
    if not os.path.exists(input_qrc):
        logger.warning(f"QRC file not found: {input_qrc}, skipping compilation.")
        return
    logger.info(f"Compiling {input_qrc} -> {output_py}")
    try:
        subprocess.run(["pyrcc5", input_qrc, "-o", output_py], check=True, cwd=BASE_DIR)
    except Exception as e:
        logger.error(f"Failed to compile QRC: {e}")

def generate_all_themes():
    for theme_folder in os.listdir(ICONS_DIR):
        theme_dir = os.path.join(ICONS_DIR, theme_folder)
        if os.path.isdir(theme_dir):
            theme_name = theme_folder
            qrc_path = os.path.join(BASE_DIR, f"resources_{theme_name}.qrc")
            rcc_py = os.path.join(BASE_DIR, f"resources_{theme_name}_rc.py")
            if generate_qrc(theme_name, theme_dir, qrc_path):
                compile_qrc(qrc_path, rcc_py)
            generate_icon_class(theme_name, theme_dir)

def clean_previous_generated(base_dir: str, icons_dir: str, confirm_delete: bool = True):
    removed_files = []
    for theme_folder in os.listdir(icons_dir):
        theme_dir = os.path.join(icons_dir, theme_folder)
        if not os.path.isdir(theme_dir):
            continue
        theme_name = theme_folder
        qrc_file = os.path.join(base_dir, f"resources_{theme_name}.qrc")
        rc_file = os.path.join(base_dir, f"resources_{theme_name}_rc.py")
        icon_file = os.path.join(base_dir, f"{theme_name}_icon.py")

        for f in [qrc_file, rc_file, icon_file]:
            if os.path.exists(f):
                removed_files.append(f)

    if removed_files:
        logger.info("Previous generated files detected:")
        for f in removed_files:
            logger.info(f"  - {f}")
        if confirm_delete:
            ans = input("Delete these files and regenerate? [y/N]: ").strip().lower()
            if ans != "y":
                logger.info("Aborted by user. No files were deleted.")
                return False
        for f in removed_files:
            try:
                os.remove(f)
                logger.info(f"Deleted: {f}")
            except Exception as e:
                logger.error(f"Failed to delete {f}: {e}")
    else:
        logger.info("No previous generated files detected.")
    return True

# === Main Entrypoint ===

if __name__ == "__main__":
    try:
        if clean_previous_generated(BASE_DIR, ICONS_DIR, confirm_delete=True):
            generate_all_themes()
    except Exception:
        logger.error("❌ Error occurred during resource generation:")
        logger.error(traceback.format_exc())
