import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import logging
logger = logging.getLogger(__name__)
import re
import subprocess
import traceback
from xml.dom import minidom
from xml.etree.ElementTree import Element, SubElement, tostring

import prism_ui.utils.logger  


# === Config Section ===
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ASSETS_DIR = os.path.join(BASE_DIR, "resource", "icon")

THEMES = {
    "blender": os.path.join(ASSETS_DIR, "blender_icons"),
    "winui": os.path.join(ASSETS_DIR, "winui_icons"),
    "custom": os.path.join(ASSETS_DIR, "custom_icons"),
}
# === Utility Functions ===

def sanitize_name(name: str, used_names: set) -> str:
    base = os.path.splitext(name)[0]
    base = re.sub(r"[^a-zA-Z0-9]+", "_", base)
    base = base.upper()
    if base and base[0].isdigit():
        base = "_" + base

    new_name = base
    counter = 2
    while new_name in used_names:
        new_name = f"{base}_{counter}"
        counter += 1

    used_names.add(new_name)
    return new_name

def add_files_from_dir(qresource, directory: str, exts: list[str], qrc_base_dir: str, found_any_flag=None):
    found_any = False
    logger.info(f"Add files from directory: {directory}")

    if os.path.isdir(directory):
        for root, _, files in os.walk(directory):
            for file in files:
                if any(file.lower().endswith(ext) for ext in exts):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, qrc_base_dir).replace("\\", "/")
                    SubElement(qresource, "file").text = rel_path
                    logger.info(f" + Adding resource file: {rel_path}")
                    found_any = True
    else:
        logger.error(f"⚠️ Folder not found: {directory}")

    if found_any_flag is not None:
        found_any_flag[0] = found_any
    return found_any

# === Per-theme generate functions ===

def generate_qrc(theme_name: str, theme_dir: str, output_qrc_path: str):
    logger.info(f"🔧 [{theme_name}] Generating Qt Resource Collection (qrc) file...")
    rcc = Element("RCC")
    qresource = SubElement(rcc, "qresource", prefix="/")

    found_any = [False]
    if os.path.isdir(theme_dir):
        for root, _, files in os.walk(theme_dir):
            for file in files:
                if file.lower().endswith(".svg"):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, ASSETS_DIR).replace("\\", "/")
                    SubElement(qresource, "file").text = rel_path
                    logger.info(f" + Adding resource file: {rel_path}")
                    found_any[0] = True

    if not found_any[0]:
        logger.warning(f"⚠️ [{theme_name}] Warning: No resource files found to add to the qrc.")

    xml_str = tostring(rcc, encoding="utf-8").decode("utf-8")
    dom = minidom.parseString(xml_str)
    pretty_xml = dom.toprettyxml(indent="  ")
    pretty_xml_lines = pretty_xml.splitlines()
    if pretty_xml_lines and pretty_xml_lines[0].strip().startswith("<?xml"):
        pretty_xml_lines = pretty_xml_lines[1:]
    pretty_xml_no_declaration = "\n".join(pretty_xml_lines)

    with open(output_qrc_path, "w", encoding="utf-8") as f:
        f.write(pretty_xml_no_declaration)

    logger.info(f"✅ [{theme_name}] QRC file generated: {output_qrc_path}")

def generate_icon_class(theme_name: str, theme_dir: str, output_icon_py_path: str):
    logger.info(f"🔧 [{theme_name}] Generating Icon Python class...")
    used_names = set()
    lines = [
        f"# Auto-generated by icon_resource_generator.py - Do not edit manually",
        f"# Generated on: 2025-06-25",
        "",
        "from PyQt5.QtGui import QIcon, QPixmap, QColor, QPainter",
        "from PyQt5.QtSvg import QSvgRenderer",
        "from PyQt5.QtCore import QSize, Qt",
        "",
        "class IconAccessor(str):",
        "    def __eq__(self, other):",
        "        return str(self) == str(other)",
        "",
        "    def __call__(self, color: str = None, size: QSize = QSize(16, 16)) -> QIcon:",
        "        if color is None or not self.lower().endswith('.svg'):",
        "            return QIcon(self)",
        "",
        "        renderer = QSvgRenderer(self)",
        "        pixmap = QPixmap(size)",
        "        pixmap.fill(Qt.transparent)",
        "",
        "        painter = QPainter(pixmap)",
        "        renderer.render(painter)",
        "        painter.setCompositionMode(QPainter.CompositionMode_SourceIn)",
        "        painter.fillRect(pixmap.rect(), QColor(color))",
        "        painter.end()",
        "",
        "        return QIcon(pixmap)",
        "",
        "class BlenderStyleIconMeta(type):",
        "    def __new__(mcs, name, bases, attrs):",
        "        new_attrs = {}",
        "        for key, value in attrs.items():",
        "            if isinstance(value, str) and value.startswith(':/'):",
        "                new_attrs[key] = IconAccessor(value)",
        "            else:",
        "                new_attrs[key] = value",
        "        return super().__new__(mcs, name, bases, new_attrs)",
        "",
        f"class {theme_name.capitalize()}Icon(metaclass=BlenderStyleIconMeta):",
        '    """',
        f"    Auto-generated icons for the '{theme_name}' theme.",
        "",
        "    Attributes",
        "    ----------",
        "    Each attribute is a Qt resource path (e.g., ':/blender_icons/folder/icon.svg'),",
        "    and can also be called as a function to return a `QIcon` instance.",
        "",
        "    Examples",
        "    --------",
        f"    Use as a raw path:",
        f"        QPixmap({theme_name.capitalize()}Icon.ICON_NAME)",
        "",
        f"    Use as a QIcon:",
        f"        button.setIcon({theme_name.capitalize()}Icon.ICON_NAME())",
        f"        button.setIcon({theme_name.capitalize()}Icon.ICON_NAME('#ff6600'))",
        "",
        "    Notes",
        "    -----",
        "    - All icons are registered in Qt resource system via .qrc/.py",
        "    - Icon names are uppercase, sanitized from original filenames",
        '    """',
    ]

    has_any = False

    if os.path.isdir(theme_dir):
        for root, _, files in os.walk(theme_dir):
            for file in sorted(files):
                if file.lower().endswith(".svg"):
                    relative_path = os.path.relpath(os.path.join(root, file), theme_dir).replace("\\", "/")
                    const_name = sanitize_name(file, used_names)
                    path = f":/{theme_name}_icons/{relative_path}"  # e.g. :/blender/icon.svg
                    lines.append(f"    {const_name} = \"{path}\"")
                    has_any = True

    if not has_any:
        lines.append("    pass")

    lines.append("")

    with open(output_icon_py_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"✅ [{theme_name}] Icon class generated: {output_icon_py_path}")

def compile_qrc(theme_name: str, input_qrc: str, output_py: str):
    logger.info(f"🔧 [{theme_name}] Compiling QRC to Python module...")
    try:
        subprocess.run(
            ["pyrcc5", input_qrc, "-o", output_py],
            check=True,
            shell=False
        )
        logger.info(f"✅ [{theme_name}] QRC compiled to Python: {output_py}")
    except FileNotFoundError:
        logger.error(f"❌ [{theme_name}] Error: `pyrcc5` not found. Please install PyQt5 or ensure it's in your PATH.")
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ [{theme_name}] Error running pyrcc5: {e}")

def generate_for_theme(theme_name: str, theme_dir: str):
    if not os.path.isdir(theme_dir):
        logger.warning(f"⚠️ [{theme_name}] Theme directory not found: {theme_dir}. Skipping generation.")
        return

    logger.info(f"=== Start processing theme: {theme_name} ===")

    output_qrc_path = os.path.join(ASSETS_DIR, f"resources_{theme_name}.qrc")
    output_rcc_py_path = os.path.join(ASSETS_DIR, f"resources_{theme_name}_rc.py")
    output_icon_py_path = os.path.abspath(os.path.join(BASE_DIR, "common", f"{theme_name}_icon.py"))

    generate_qrc(theme_name, theme_dir, output_qrc_path)
    compile_qrc(theme_name, output_qrc_path, output_rcc_py_path)
    generate_icon_class(theme_name, theme_dir, output_icon_py_path)

    logger.info(f"=== Finished processing theme: {theme_name} ===\n")

# === Main Entrypoint ===

if __name__ == "__main__":
    try:
        for theme_name, theme_dir in THEMES.items():
            generate_for_theme(theme_name, theme_dir)
    except Exception:
        logger.error("❌ Error occurred during resource generation:")
        logger.error(traceback.format_exc())
