from prism_ui.common.base_colors import BaseColors

class LightThemeColors(BaseColors):
    # Text type Color
    TextFillColorPrimaryBrush = "#000000"
    TextFillColorSecondaryBrush = "#666666"
    TextFillColorTertiaryBrush = "#999999"
    TextFillColorDisabledBrush = "#C2C2C2"
    AccentTextFillColorPrimaryBrush = "#0078D4"
    AccentTextFillColorSecondaryBrush = "#66C6FF"
    AccentTextFillColorTertiaryBrush = "#A0E2FF"
    AccentTextFillColorDisabledBrush = "#B0B0B0"
    TextOnAccentFillColorPrimaryBrush = "#FFFFFF"
    TextOnAccentFillColorSecondaryBrush = "#FBFBFB"
    TextOnAccentFillColorDisabledBrush = "#FFFFFF"
    TextOnAccentFillColorSelectedTextBrush = "#FFFFFF"
    # Fill type Color
    ControlFillColorDefaultBrush = "#FBFBFB"
    ControlFillColorSecondaryBrush = "#F6F6F6"
    ControlFillColorTertiaryBrush = "#F5F5F5"
    ControlFillColorQuarternaryBrush = "#F5F5F5"
    ControlFillColorDisabledBrush = "#F5F5F5"
    ControlFillColorTransparentBrush = "#F3F3F3"
    ControlFillColorInputActiveBrush = "#FFFFFF"
    ControlAltFillColorTransparentBrush = "#F3F3F3"
    ControlAltFillColorSecondaryBrush = "#EDEDED"
    ControlAltFillColorTertiaryBrush = "#E5E5E5"
    ControlAltFillColorQuarternaryBrush = "#DCDCDC"
    ControlAltFillColorDisabledBrush = "#F3F3F3"
    ControlSolidFillColorDefaultBrush = "#FFFFFF"
    ControlStrongFillColorDefaultBrush = "#868686"
    ControlStrongFillColorDisabledBrush = "#A6A6A6"
    SubtleFillColorTransparentBrush = "#F3F3F3"
    SubtleFillColorSecondaryBrush = "#EAEAEA"
    SubtleFillColorTertiaryBrush = "#EDEDED"
    SubtleFillColorDisabledBrush = "#F3F3F3"
    ControlOnImageFillColorDefaultBrush = "#FCFCFC"
    ControlOnImageFillColorSecondaryBrush = "#F3F3F3"
    ControlOnImageFillColorTertiaryBrush = "#EBEBEB"
    ControlOnImageFillColorDisabledBrush = "#F3F3F3"
    AccentFillColorDefaultBrush = "#0067C0"
    AccentFillColorSecondaryBrush = "#1975C5"
    AccentFillColorTertiaryBrush = "#3183CA"
    AccentFillColorDisabledBrush = "#BFBFBF"
    AccentFillColorSelectedTextBackgroundBrush = "#0078D4"

class DarkThemeColors(BaseColors):
    # Text type Color
    TextFillColorPrimaryBrush = "#FFFFFF"
    TextFillColorSecondaryBrush = "#CCCCCC"
    TextFillColorTertiaryBrush = "#969696"
    TextFillColorDisabledBrush = "#717171"
    AccentTextFillColorPrimaryBrush = "#99EBFF"
    AccentTextFillColorSecondaryBrush = "#99EBFF"
    AccentTextFillColorTertiaryBrush = "#4CC2FF"
    AccentTextFillColorDisabledBrush = "#717171"
    TextOnAccentFillColorPrimaryBrush = "#000000"
    TextOnAccentFillColorSecondaryBrush = "#101010"
    TextOnAccentFillColorDisabledBrush = "#969696"
    TextOnAccentFillColorSelectedTextBrush = "#FFFFFF"
    # Fill type Color
    ControlFillColorDefaultBrush = "#2D2D2D"
    ControlFillColorSecondaryBrush = "#323232"
    ControlFillColorTertiaryBrush = "#272727"
    ControlFillColorQuarternaryBrush = "#272727"
    ControlFillColorDisabledBrush = "#2A2A2A"
    ControlFillColorTransparentBrush = "#202020"
    ControlFillColorInputActiveBrush = "#1F1F1F"
    ControlAltFillColorTransparentBrush = "#202020"
    ControlAltFillColorSecondaryBrush = "#1D1D1D"
    ControlAltFillColorTertiaryBrush = "#2A2A2A"
    ControlAltFillColorQuarternaryBrush = "#303030"
    ControlAltFillColorDisabledBrush = "#202020"
    ControlSolidFillColorDefaultBrush = "#454545"
    ControlStrongFillColorDefaultBrush = "#9A9A9A"
    ControlStrongFillColorDisabledBrush = "#575757"
    SubtleFillColorTransparentBrush = "#202020"
    SubtleFillColorSecondaryBrush = "#2D2D2D"
    SubtleFillColorTertiaryBrush = "#292929"
    SubtleFillColorDisabledBrush = "#202020"
    ControlOnImageFillColorDefaultBrush = "#1E1E1E"
    ControlOnImageFillColorSecondaryBrush = "#1A1A1A"
    ControlOnImageFillColorTertiaryBrush = "#131313"
    ControlOnImageFillColorDisabledBrush = "#1E1E1E"
    AccentFillColorDefaultBrush = "#4CC2FF"
    AccentFillColorSecondaryBrush = "#47B1E8"
    AccentFillColorTertiaryBrush = "#42A1D2"
    AccentFillColorDisabledBrush = "#434343"
    AccentFillColorSelectedTextBackgroundBrush = "#0078D4"